options:
  default-gateways:
    default: istio-gateway
    description: Comma-separated list of gateways to create by default
    type: string
  namespaced-custom-gateways:
    default: ""
    description: Comma-separated list of namespaced custom gateways to use
    type: string
