name: Publish bundle to charm store

on:
  - push
  # push:
  #   branches:
  #     - master

jobs:
  build:
    name: Publish bundle
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        set -eux
        sudo snap install juju-bundle --classic
        sudo snap install charmcraft --classic --channel=latest/edge

    - run: juju-bundle publish
      env:
        CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}
